server:
  port: 8082

spring:
  application:
    name: pudding-api
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
        tags: api,service
      config:
        enabled: true
        format: YAML
        data-key: data
        # 指定配置前缀，如果不指定，默认使用应用名
        prefix: config
        default-context: application
        profile-separator: ','
