version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs

  pudding-user:
    build:
      context: .
      dockerfile: pudding-user/Dockerfile
    container_name: pudding-user
    ports:
      - "8081:8081"
    environment:
      - NACOS_ADDR=nacos:8848
    depends_on:
      - nacos

  pudding-gateway:
    build:
      context: .
      dockerfile: pudding-gateway/Dockerfile
    container_name: pudding-gateway
    ports:
      - "8080:8080"
    environment:
      - NACOS_ADDR=nacos:8848
    depends_on:
      - nacos

volumes:
  nacos-data:
  nacos-logs:
