# Consul中的pudding-api配置
# 路径: config/pudding-api/data

# Jackson配置
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# 外部API配置
external:
  api:
    jsonplaceholder:
      url: https://jsonplaceholder.typicode.com

# Retrofit 全局配置
retrofit:
  # 全局日志打印配置
  global-log:
    enable: true
    log-level: info
    log-strategy: basic
    aggregate: true

  # 全局重试配置
  global-retry:
    enable: false  # 使用声明式重试
    interval-ms: 100
    max-retries: 2
    retry-rules:
      - response_status_not_2xx
      - occur_io_exception

  # 全局超时时间配置
  global-timeout:
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    connect-timeout-ms: 5000
    call-timeout-ms: 0

  # 熔断降级配置
  degrade:
    degrade-type: resilience4j
    global-resilience4j-degrade:
      enable: false  # 使用现有的 Resilience4j 配置

# Resilience4j配置
resilience4j:
  circuitbreaker:
    instances:
      jsonplaceholder:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

  retry:
    instances:
      jsonplaceholder:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

  ratelimiter:
    instances:
      jsonplaceholder:
        registerHealthIndicator: true
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 3s

  timelimiter:
    instances:
      jsonplaceholder:
        timeoutDuration: 2s
        cancelRunningFuture: true

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,ratelimiters
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.milkpudding.api: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.consul: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{50}] - %msg%n'

# 业务配置
app:
  api:
    # 外部API调用配置
    external:
      timeout: 5000
      max-retries: 3
      rate-limit: 100
    # 缓存配置
    cache:
      ttl: 300 # 5分钟
      max-size: 1000
    # 数据验证配置
    validation:
      strict-mode: true
      max-request-size: 10MB
