server:
  port: 8081

spring:
  application:
    name: pudding-user
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
        tags: user,api
      config:
        enabled: true
        format: YAML
        data-key: data

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# 日志配置
logging:
  level:
    root: INFO
    com.milkpudding.user: DEBUG
    org.springframework.cloud.consul: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{50}] - %msg%n'
